export const GET_ATTRIBUTES_REQUEST = "GET_ATTRIBUTES_REQUEST"
export const GET_ATTRIBUTES_SUCCESS = "GET_ATTRIBUTES_SUCCESS"
export const GET_ATTRIBUTES_FAIL = "GET_ATTRIBUTES_FAIL"

export const UPDATE_ATTRIBUTE_REQUEST = "UPDATE_ATTRIBUTE_REQUEST"
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS"
export const UPDATE_ATTRIBUTE_FAIL = "UPDATE_ATTRIBUTE_FAIL"
export const UPDATE_ATTRIBUTE_RESET = "UPDATE_ATTRIBUTE_RESET"

export const ADD_ATTRIBUTE_REQUEST = "ADD_ATTRIBUTE_REQUEST"
export const ADD_ATTRIBUTE_SUCCESS = "ADD_ATTRIBUTE_SUCCESS"
export const ADD_ATTRIBUTE_FAIL = "ADD_ATTRIBUTE_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"