export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

export const GET_SINGLE_ORDERS_REQUEST = "GET_SINGLE_ORDERS_REQUEST"
export const GET_SINGLE_ORDERS_SUCCESS = "GET_SINGLE_ORDERS_SUCCESS"
export const GET_SINGLE_ORDERS_FAIL = "GET_SINGLE_ORDERS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"