export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_FAIL = "GET_ADDRESS_FAIL"

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST"
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS"
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL"

export const REMOVE_ADDRESS_REQUEST = "REMOVE_ADDRESS_REQUEST"
export const REMOVE_ADDRESS_SUCCESS = "REMOVE_ADDRESS_SUCCESS"
export const REMOVE_ADDRESS_FAIL = "REMOVE_ADDRESS_FAIL"

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST"
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS"
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL"