export const CART_ITEMS_REQUEST = "CART_ITEMS_REQUEST"
export const CART_ITEMS_SUCCESS = "CART_ITEMS_SUCCESS"
export const CART_ITEMS_FAIL = "CART_ITEMS_FAIL"

export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_FAIL = "ADD_CART_FAIL"

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL"

export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS"
export const REMOVE_CART_FAIL = "REMOVE_CART_FAIL"