export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

export const PRODUCT_DETAIL_REQUESTS = "PRODUCT_DETAIL_REQUESTS"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"


export const FILTER_PRODUCT_REQUESTS = "FILTER_PRODUCT_REQUESTS"
export const FILTER_PRODUCT_SUCCESS = "FILTER_PRODUCT_SUCCESS"
export const FILTER_PRODUCT_FAIL = "FILTER_PRODUCT_FAIL"


export const CREATE_REVIEW_REQUESTS = "CREATE_REVIEW_REQUESTS"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL"
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET"

export const USER_PRODUCTS_REVIEW_REQUEST = "USER_PRODUCTS_REVIEW_REQUESTS"
export const USER_PRODUCTS_REVIEW_SUCCESS = "USER_PRODUCTS_REVIEW_SUCCESS"
export const USER_PRODUCTS_REVIEW_FAIL = "USER_PRODUCTS_REVIEW_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"