export const LOGIN_REQUEST = "LOGIN_REQUEST" 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" 
export const LOGIN_FAIL = "LOGIN_FAIL" 

export const REGISTER_REQUEST = "REGISTER_REQUEST" 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS" 
export const REGISTER_FAIL = "REGISTER_FAIL" 

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST" 
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS" 
export const LOAD_USER_FAIL = "LOAD_USER_FAIL" 


export const LOGOUT_REQUEST = "LOGOUT_REQUEST" 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS" 
export const LOGOUT_FAIL = "LOGOUT_FAIL" 

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST" 
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS" 
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL" 
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET" 

export const CHANGE_PSWD_REQUEST = "CHANGE_PSWD_REQUEST" 
export const CHANGE_PSWD_SUCCESS = "CHANGE_PSWD_SUCCESS" 
export const CHANGE_PSWD_FAIL = "CHANGE_PSWD_FAIL" 
export const CHANGE_PSWD_RESET = "CHANGE_PSWD_RESET" 

export const FORGOT_PSWD_REQUEST = "FORGOT_PSWD_REQUEST" 
export const FORGOT_PSWD_SUCCESS = "FORGOT_PSWD_SUCCESS" 
export const FORGOT_PSWD_FAIL = "FORGOT_PSWD_FAIL"

export const RESET_PSWD_REQUEST = "RESET_PSWD_REQUEST" 
export const RESET_PSWD_SUCCESS = "RESET_PSWD_SUCCESS" 
export const RESET_PSWD_FAIL = "RESET_PSWD_FAIL" 