export const WISHLIST_ADD_REQUEST = "WISHLIST_ADD_REQUEST"
export const WISHLIST_ADD_SUCCESS = "WISHLIST_ADD_SUCCESS"
export const WISHLIST_ADD_FAIL = "WISHLIST_ADD_FAIL"

export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST"
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS"
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL"

export const REMOVE_WISHLIST_REQUEST = "REMOVE_WISHLIST_REQUEST"
export const REMOVE_WISHLIST_SUCCESS = "REMOVE_WISHLIST_SUCCESS"
export const REMOVE_WISHLIST_FAIL = "REMOVE_WISHLIST_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"